services:
  - type: web
    name: laravel-ecommerce
    env: php
    plan: free
    buildCommand: |
      # Install PostgreSQL dependencies and PHP extension
      apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo_pgsql
      # Install dependencies for Laravel
      composer install --no-dev --optimize-autoloader
      # Clear config cache, generate app key, and run migrations
      php artisan config:clear
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
